version: '2'
services:
  influxdb:
    image: donn/influxdb
    restart: always
    privileged: true
    ports:
      - 8083:8083/tcp
      - 8086:8086/tcp
      - 25826:25826/udp
    volumes:
      - /srv/influxdb/:/data/
    environment:
      - ADMIN_USER=root
      - INFLUXDB_INIT_PWD=myPassw0rd
      - PRE_CREATE_DB=my_db
      - COLLECTD_ENABLED=true
      - COLLECTD_DB=my_db
      - COLLECTD_BINDING=:25826
    logging:
      options:
        max-size: "10m"
        max-file: "2"
