version: '3'
services:
  grafana:
    image: grafana/grafana:7.3.7
    restart: always
    ports:
      - 3000:3000/tcp
    # https://grafana.com/docs/grafana/latest/installation/docker/#migrate-to-v73-or-later
    # https://community.grafana.com/t/new-docker-install-with-persistent-storage-permission-problem/10896/5
    # On b00 laptop-server, user=donn is id=1000.
    user: '1000:1000'
    volumes:
      - /srv/grafana/:/var/lib/grafana
    environment:
      # Don't auto-logout the user.
      # grafana.ini to env var:
      # GF + <section_name> + <key_name>
      # ref: https://grafana.com/docs/grafana/latest/administration/configuration/
      - GF_AUTH_LOGIN_MAXIMUM_LIFETIME_DURATION=365d
      - GF_AUTH_TOKEN_ROTATION_INTERVAL_MINUTES=525600
    logging:
      options:
        max-size: "10m"
        max-file: "2"
