version: '3'
services:
  collectd:
    # There's no src Dockerfile for this collectd-snmp image.
    # See gDoc "collectd + snmp at home" for how it was built.
    # Versioning is managed in hub.docker.com/u/donn
    image: donn/collectd-snmp-stretch-backports:fox_2019_10
    restart: always
    command: tail -f /dev/null
    volumes:
      - /srv/collectd/:/data/
    logging:
      options:
        max-size: "10m"
        max-file: "2"
