# Start service with:
#  docker stack deploy -c docker-compose.yml collectd
# (Not with 'docker-compose up')

version: '3'
services:
  collectd:
    # There's no src Dockerfile for this collectd-snmp image.
    # See gDoc "collectd + snmp at home" for how it was built.
    # Container is commit'd and image pushed to private docker repo.
    #
    # 'fox' server died. moved influxdb, collectd, grafana to 'b00' laptop-server 2021/10/30
    image: fran.xloha.com/collectd-snmp-stretch-backports:donn_b00_20211030
    deploy:
      restart_policy:
        # https://docs.docker.com/compose/compose-file/#restart_policy
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
    command: >
      bash -c "/usr/sbin/collectd -C /etc/collectd/collectd.conf &&
      tail -f /dev/null"
    volumes:
      - /srv/collectd/:/data/
    logging:
      options:
        max-size: "10m"
        max-file: "2"
